/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ncsu_dotscan_MainActivity */

#ifndef _Included_com_ncsu_dotscan_MainActivity
#define _Included_com_ncsu_dotscan_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ncsu_dotscan_MainActivity
 * Method:    getDot
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT jint JNICALL Java_com_ncsu_dotscan_MainActivity_getDot
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
